### ISSUE TITLE
Unhandled Exception: System.AggregateException: One or more errors occurred. —-

### ISSUE THREAD

**Issue by HellScre4m** [GreyWolfDev/Werewolf#289]
`Unhandled Exception: System.AggregateException: One or more errors occurred. —-
> System.Net.Http.HttpRequestException: An error occurred while sending the requ
est. —-> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpHandler.SetSessionHandleTlsOptions(SafeWinHttpHandl
e sessionHandle)
   at System.Net.Http.WinHttpHandler.SetSessionHandleOptions(SafeWinHttpHandle s
essionHandle)
   at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(WinHttpRequestSta
te state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   —- End of inner exception stack trace —-
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
—- End of stack trace from previous location where exception was thrown —-
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   —- End of inner exception stack trace —-
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Werewolf_Node.Program.Main(String[] args) in G:\Test\Werewolf\Werewolf for
 Telegram\Werewolf Node\Program.cs:line 101`

**Comment by Olfi01** [comment]
A bit more specific description would be nice, if the issue is still present. Otherwise, this issue might be closed.

**Comment by Olgabrezel** [comment]
I'll close this, I doubt anything will happen here anyway :')
