### ISSUE TITLE
Object reference not set to an instance of an object and Others

### ISSUE THREAD

**Issue by anazhd** [GreyWolfDev/Werewolf#439]
I'm getting this error on Control.exe

>    Object reference not set to an instance of an object.
at Werewolf_Control.Helpers.Bot.ApiOnStatusChanged(Object sender, StatusChangeEventArgs statusChangeEventArgs) in D:\TG\Werewolf\Werewolf for Telegram\Werewolf Control\Helpers\Bot.cs:line 184
   at Telegram.Bot.Client.OnStatusChanged(StatusChangeEventArgs e) in D:\TG\Werewolf\Werewolf for Telegram\Telegram.Bot\Client.cs:line 61
   at Telegram.Bot.Client.<Receive>d__57.MoveNext() in D:\TG\Werewolf\Werewolf for Telegram\Telegram.Bot\Client.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionCo

And also after running Control.exe, Node.exe will spawn but refused to connect, of course because Control.exe was throwing the error above and exited.

> Error in KeepAlive: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)

>Error in reconnect: No connection could be made because the target machine actively refused it 127.0.0.1:8090
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at TcpFramework.SimpleTcpClient.Connect(String hostNameOrIpAddress, Int32 port) in D:\TG\Werewolf\Werewolf for Telegram\TcpFramework\SimpleTcpClient.cs:line 41
   at Werewolf_Node.Program.Connect() in D:\TG\Werewolf\Werewolf for Telegram\Werewolf Node\Program.cs:line 381

I changed both port on release (control & node) to some other number just to see if there is any other service running on the same port but nothing there. Upon checking various forums and looking into System.Net, couldn't find anything wrong. I'm also using about the same technique for my work project, I doubt this have anything to do with network routing or firewall.

Not sure where I did wrong or a few step I missed.
Directory list
```
Root
|_Languages
|_Prod
    |_Control
        |_<everything from control\bin\Release>
    |_Node 1
        |_<everything from node\bin\Release>
    |_Logs
```

**Comment by Olfi01** [comment]
Have you made sure the firewall is configured to allow werewolf access to the internet?

**Comment by anazhd** [comment]
Tried disabling firewall completely, tried selective inbound outbound. The control can get the bot name from the telegram api though. So I guess I got everything in order, just 2 binary, Control.exe for the bot and node spawner, and the node.exe itself.

I'm running it on Windows 10, there's that. Haven't tried on Windows Server as I only have production server at the moment, wouldn't be practical to spawn a non-work stuff on it.

**Comment by Olfi01** [comment]
Have you set your token in the registry?

**Comment by anazhd** [comment]
Of course, ProductionAPI is up accordingly, Control helper able to get the key and call for the telegram api, thus it got all the bot details needed. I can see my bot name on the control.exe window.

**Comment by Olfi01** [comment]
Oh, the line where the exception occurred accesses the db... have you set up an sql server and configured the bot to connect to it?

**Comment by anazhd** [comment]
Should be working fine as wrong login/connection string will throw different error like **below**:

> The underlying provider failed on Open.
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvid

Tried on two machine with 2 different config, same result (1st post)
1. sqlexpress14 - using windows auth and sql account auth
2. sqlexpress14 (new setup on different machine) - using windows auth

So the error quoted on my 1st post above is something else. Something to do with the control helper didn't receive anything white await. while the node couldn't connect to something which I have no idea  what 🤔

**Comment by Olfi01** [comment]
The db might be set up wrongly. All the tables have to already be created for it to work

**Comment by Olfi01** [comment]
https://pastebin.com/hL8NK0vn
Here is a sql script that should be able to set up the db for you

**Comment by anazhd** [comment]
tried recreate using the sql script on this git, also the one you give.

> Commands completed successfully.
![sql](https://i.imgur.com/GG27o7O.png)

I must admit, I'm using sqlexpress14 (2017), but I don't see any difference or something missing out there. All tables and all stored proc. Are you on sql server 2014?

**Comment by anazhd** [comment]
Yup, as I expect, changing to sql server 2014 wont do anything. Same error

**Comment by Olfi01** [comment]
The one in the git is outdated as far as I know. As for the error, I honestly have no idea any more

**Comment by Olfi01** [comment]
Have you tried running it in debug mode from visual studio directly?

**Comment by anazhd** [comment]
Tried debug mode and more errors because of different path between debug and release. Went back building the binaries, and I came across Botan. Do I need the BotanReleaseAPI on the registry or just comment it out? Previously I commented like so according to #228 

Node\Program.cs line 88 and 90.
> #if BETA || DEBUG
            var aToken = key.GetValue("BotanBetaAPI").ToString();
#else
            //var aToken = key.GetValue("BotanReleaseAPI").ToString();
#endif
            //Analytics = new BotanIO.Api.Botan(aToken);

**Comment by Olfi01** [comment]
i just gave it a fake token yea

**Comment by Olfi01** [comment]
Commenting out should work too

**Comment by Olfi01** [comment]
Also, you should configure VS to start bot control and node in debug

**Comment by anazhd** [comment]
Running release on debug mode, with both control and node as startup.

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Werewolf Node
>   StackTrace:
>    at Werewolf_Node.Program.Main(String[] args) in E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Node\Program.cs:line 81

line 81
```
var key =RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64).OpenSubKey("SOFTWARE\\Werewolf");
```

proceed with Step Over then I got this on the function `private static void NewNode()
`
> System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot start process because a file name has not been provided.
  Source=System
  StackTrace:
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Werewolf_Control.Program.NewNode() in E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Control\Program.cs:line 412
   at Werewolf_Control.Program.NodeMonitor() in E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Control\Program.cs:line 386
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

step again and it break.

**Comment by Olfi01** [comment]
Hm NewNode shouldn't even be needed to be called, are you really starting both Node and Control?

**Comment by anazhd** [comment]
Yes, both on startup. I'm pretty sure, quite familiar with VS because I do asp.net eveyday at work.

While runing "debug" on debug mode

> System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Control\bin\Logs\apireceiveerror.log'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Werewolf_Control.Helpers.Bot.ApiOnReceiveError(Object sender, ReceiveErrorEventArgs receiveErrorEventArgs) in E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Control\Helpers\Bot.cs:line 206
   at Telegram.Bot.Client.OnReceiveError(ReceiveErrorEventArgs e) in E:\wolf\o\Werewolf\Werewolf for Telegram\Telegram.Bot\Client.cs:line 89
   at Telegram.Bot.Client.<Receive>d__57.MoveNext() in E:\wolf\o\Werewolf\Werewolf for Telegram\Telegram.Bot\Client.cs:line 252
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

It says, "mscorlib.pdb not loaded"
I step into, it break Control.exe but then again the node will throw this again. Of course this is caused because the control.exe process is nowhere to be found.

> Error in KeepAlive: An existing connection was forcibly closed by the remote host
>    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
> 
> Error in reconnect: No connection could be made because the target machine actively refused it 127.0.0.1:9049
>    at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
>    at TcpFramework.SimpleTcpClient.Connect(String hostNameOrIpAddress, Int32 port) in E:\wolf\o\Werewolf\Werewolf for Telegram\TcpFramework\SimpleTcpClient.cs:line 41
>    at Werewolf_Node.Program.Connect() in E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Node\Program.cs:line 387

**Comment by Olfi01** [comment]
The lower error only means that the node didn't find a control to connect to, yes.
As you can see in the path `E:\wolf\o\Werewolf\Werewolf for Telegram\Werewolf Control\bin\Logs\apireceiveerror.log`, it's searching below control instead of on the same level. Let me quickly check something in my own setup...

**Comment by anazhd** [comment]
![debug](https://i.imgur.com/YDKGnlL.png)

While the control did found the node

**Comment by Olfi01** [comment]
Ah well maybe the node was a bit too quick, if the error is just there once it'll just retry. You only need to worry if that error keeps spamming over and over

**Comment by Olfi01** [comment]
I didn't find anything in my setup, btw

**Comment by anazhd** [comment]
Interstingly, on release, when I run Control.exe, it will load everything accordingly first before spawning the node. After that, Control.exe will just break and throw the error on post 1 `ApiOnStatusChanged`. It detects the node, but the node can't reach the control. Well this seems tiring to look again and again haha.

Can you git clone a new set and try to reproduce? I also tried your fork but it's the same thing.

**Comment by Olfi01** [comment]
Did you try the debug branch of my fork, though?

**Comment by anazhd** [comment]
I'm on it. Give me a moment

**Comment by Olfi01** [comment]
So, I cloned the repo again and started Control + Node in debug mode, everything looks fine to me, output is getting spammed with exceptions, but it works

**Comment by Olfi01** [comment]
![image](https://user-images.githubusercontent.com/22056746/55000143-27256780-4fd2-11e9-8409-264f0ba33f27.png)
This is how my registry looks. The crossed out section are my bot's tokens

**Comment by anazhd** [comment]
Great. Your debug branch is working fine. But the bot didn't respond to anything when in group. Already configure on botfather. Will try release and run to see how

**Comment by Olfi01** [comment]
You probably will need to either make your bot admin or append the commands with the `@botusername` suffix

**Comment by anazhd** [comment]
The bot immediately left after I add. Something is not right there

**Comment by Olfi01** [comment]
Oh, in debug mode it does that unless you specify it shouldn't

**Comment by anazhd** [comment]
I see. Then again, after trying run release, control.exe just exit with the same error.
```
Root
|_Languages
|_Prod
    |_Control
        |_<everything from control\bin\Release>
    |_Node 1
        |_<everything from node\bin\Release>
    |_Logs
```

Is this the correct way to do it? Nothing else needed?

**Comment by Olfi01** [comment]
I don't know, I haven't tried running release yet. As for debug, you can find the code that causes the leaving in Control/Handlers/UpdateHandler.cs

**Comment by Olfi01** [comment]
I'm trying to get release to run, gonna come back to you once I found something

**Comment by anazhd** [comment]
I guess I'll try this on release

**Comment by Olfi01** [comment]
I am trying right now, and it seems the link needs to be something else. I'm checking what it is rn

**Comment by Olfi01** [comment]
OH no nevermind my bad the link is good, but you can't start a game unless you set the file identifiers for the gifs correctly

**Comment by anazhd** [comment]
> To solve that, just add the entry with Id 1, name whatever you want, and link most likely the username of your bot, I guess.

Nothing to do change or just add an entry without link?

**Comment by Olfi01** [comment]
No, link can't be null, just enter the username of your bot there for now

**Comment by anazhd** [comment]
The bot status would be?

**Comment by Olfi01** [comment]
I got it tow work by just setting every gifs ID to the id of one I retrieved by using !learngif

**Comment by Olfi01** [comment]
BotStatus is irrelevant, just dont leave it empty

**Comment by Olfi01** [comment]
If this solved it for you, you might close this issue :D

**Comment by anazhd** [comment]
Technically this is not solved yet. I still can't run debug and release a working binary on the original repo.

**Comment by Olfi01** [comment]
Well, you definitely will have to modify the code if you want to run the debug configuration.

> As for debug, you can find the code that causes the leaving in Control/Handlers/UpdateHandler.cs

**Comment by Olfi01** [comment]
And what is the problem with release now?

**Comment by anazhd** [comment]
The one that I can run is not the original, it's your fork. Original repo still can't run regardless in debug or release. I can cherrypick some stuff from your fork but the point is letting GreyWolfDev team, the issue is in their current master branch.

**Comment by Olfi01** [comment]
Their master branch is (correctly) configured for the original werewolf bot. To run your own version you need to modify the code, so you probably wanna fork it yourself.

**Comment by Olfi01** [comment]
As a summary of changes: 

- Add entries into BotStatus table

- Add your group into the debug groups in `Werewolf Control/Handlers/UpdateHandler.cs`

- Set the correct file ids in `Werewolf Control/Helpers/Settings.cs`

**Comment by anazhd** [comment]
Tried another completely from scratch,

1. Add DebugAPI (telegram token), BotanBetaAPI (leave empty), BotanReleaseAPI (leave empty) string in HKLM\Software\Werewolf, making the Key having 5 String values excluding Default string value.
2. Add bot name int BotStatus table, the rest column just some random string. Using SQL Express 2017 is just fine.
3. Select Release and Build solutions. Arrange all binaries built accordingly in the right directory.
4. Start the bot (will spawn Control.exe, and control will spawn a Node.exe), communicate with the bot in PM just to see if the bot reply. If yes, type in learngif and upload a gif. Bot will reply with the gif id. Copy it somewhere and open `Werewolf Control/Helpers/Settings.cs` and `Werewolf Node/Helpers/Settings.cs` then paste it in `public static List<string> * = new List<string> { "GIF_ID_HERE" };` Do it on all 14 types on both files.
5. Stop the bot. Build the solutions again and arrange all binaries built accordingly like step 3.
6. Run the bot again, wait until Node.exe spawned. Add the bot to a group, type in `/startgame`, if the bot reply with Join button, then it's working fine. If the bot reply error, then most probably the gif id is not valid or nowhere to be found.

So far everything (Release build most importantly) is fine 👍🏻.

**Comment by Olfi01** [comment]
yea so it works now? :)

**Comment by anazhd** [comment]
Sure it is. I'll close this for now. Thanks for you help! Cheers
