### ISSUE TITLE
Problem notifying roles

### ISSUE THREAD

**Issue by parabola949** [GreyWolfDev/Werewolf#78]
Werewolf Moderator:
3.0.6071.17521
Group: -172203677 (Werewolf Gamaliel)
Language: Bahasa Indo
Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Werewolf_Node.Werewolf.GetRoleInfo(IRole role) in C:\Users\jus00091\Source\Repos\Werewolf\Werewolf for Telegram\Werewolf Node\Werewolf.cs:line 1163
   at Werewolf_Node.Werewolf.NotifyRoles() in C:\Users\jus00091\Source\Repos\Werewolf\Werewolf for Telegram\Werewolf Node\Werewolf.cs:line 1086
   at Werewolf_Node.Werewolf.GameTimer() in C:\Users\jus00091\Source\Repos\Werewolf\Werewolf for Telegram\Werewolf Node\Werewolf.cs:line 266

**Comment by renyhp** [comment]
This is very likely to be fixed... or, at least that stacktrace is not telling us much, is it? Waiting for you to close this issue @parabola949

**Comment by Olgabrezel** [comment]
This seems outdated. Closing it.
